version: '2'

networks:
  gallifrey:
    external: true

volumes:
  caddy: {}

  steemprojectscom_static:
      driver: local

  steemprojectscom_media:
      driver: local

services:
  caddy:
    build: .
    volumes:
      - steemprojectscom_static:/data/steemprojectscom_static
      - steemprojectscom_media:/data/steemprojectscom_media
      - caddy:/root/.caddy
    ports:
      - "80:80"
      - "443:443"
    external_links:
      - steemprojectscom_django-a_1:steemprojectscom_django-a
      - steemprojectscom_django-b_1:steemprojectscom_django-b
    networks:
      - gallifrey
