version: "3"

networks:
  hiveprojectsio_default:
    external: true
  steemprojectscom_default:
    external: true
  stagingsteemprojectscom_default:
    external: true
  daleksteemprojectscom_default:
    external: true
  gallifrey:
    external: true

volumes:
  caddy: {}

  # Production
  hiveprojectsio_static:
    external:
      name: hiveprojectsio_static

  hiveprojectsio_media:
    external:
      name: hiveprojectsio_media

  # Production
  steemprojectscom_static:
    external:
      name: steemprojectscom_static

  steemprojectscom_media:
    external:
      name: steemprojectscom_media

  # Staging
  stagingsteemprojectscom_static:
    external:
      name: stagingsteemprojectscom_static

  stagingsteemprojectscom_media:
    external:
      name: stagingsteemprojectscom_media

  # Dalek
  daleksteemprojectscom_static:
    external:
      name: daleksteemprojectscom_static

  daleksteemprojectscom_media:
    external:
      name: daleksteemprojectscom_media

services:
  caddy:
    build: .
    volumes:
      - hiveprojectsio_static:/data/hiveprojectsio_static
      - hiveprojectsio_media:/data/hiveprojectsio_media
      - steemprojectscom_static:/data/steemprojectscom_static
      - steemprojectscom_media:/data/steemprojectscom_media
      - stagingsteemprojectscom_static:/data/stagingsteemprojectscom_static
      - stagingsteemprojectscom_media:/data/stagingsteemprojectscom_media
      - daleksteemprojectscom_static:/data/daleksteemprojectscom_static
      - daleksteemprojectscom_media:/data/daleksteemprojectscom_media
      - caddy:/root/.caddy
    ports:
      - "80:80"
      - "443:443"
    external_links:
      - hiveprojectsio_django-a_1:hiveprojectsio_django-a
      - hiveprojectsio_django-b_1:hiveprojectsio_django-b
      - steemprojectscom_django-a_1:steemprojectscom_django-a
      - steemprojectscom_django-b_1:steemprojectscom_django-b
      - stagingsteemprojectscom_django-a_1:stagingsteemprojectscom_django-a
      - stagingsteemprojectscom_django-b_1:stagingsteemprojectscom_django-b
      - daleksteemprojectscom_django-a_1:daleksteemprojectscom_django-a
      - daleksteemprojectscom_django-b_1:daleksteemprojectscom_django-b
      - exampledjango_django_1:exampledjango_django
    networks:
      - hiveprojectsio_default
      - steemprojectscom_default
      - stagingsteemprojectscom_default
      - daleksteemprojectscom_default
      - gallifrey
